# azure-pipelines-ci.yml
#
# Copyright (c) 2020 Kano Computing Ltd.
#
# Continuous integration pipeline for the project.


trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - '*'

variables:
  major: 2
  minor: 2
  patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']), 0)]

# Customise the Build.BuildNumber variable with the version of the build.
name: '$(major).$(minor).$(patch)'

resources:
  repositories:
  - repository: templates
    type: github
    name: KanoComputing/azure-pipeline-templates
    endpoint: KanoComputing
    ref: refs/tags/2.0.6

pool:
  vmImage: 'windows-latest'


stages:
- stage:
  displayName: 'Hello'
  jobs:
  - deployment: Hello
    environment: 'Staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'Write-Host "Hello"'

  - job: MicrosoftStoreManualValidation
    displayName: 'Microsoft Store manual validation'
    pool: server
    dependsOn: [Hello]
    timeoutInMinutes: 0
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 0
      inputs:
        notifyUsers: |
          radu@kano.me
          tom@kano.me
          team-systems@kano.me
        instructions: >-
          The release to Microsoft Store has failed. If this was due to an unusually long
          execution and timeout, wait until the store submission has finalised and approve
          this step. To check on the submission, login with your Work account when visiting
          https://partner.microsoft.com/en-us/dashboard/overview
        onTimeout: 'reject'

- stage: World
  displayName: 'World'
  jobs:
  - deployment: World
    environment: 'Staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'Write-Host "World"'
